blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog/<int:pk>/update', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('mail.urls', 'mail'), namespace='mail')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserUpdateView, UserDeleteView, UserListView, UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>', email_verification, name='email-confirm'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/delete', UserDeleteView.as_view(), name='user_delete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=35, verbose_name='Phone Number', blank=True, null=True, help_text='Phone number')
    country = models.CharField(max_length=50, verbose_name='Country', blank=True, null=True, help_text='Country')
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='Avatar', blank=True, null=True, help_text='Upload your avatar')

    token = models.CharField(max_length=100, verbose_name='Token', blank=True, null=True)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        permissions = [('can_view_user', 'Can view user'), ('can_block_user', 'Can block user')]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('is_active',)

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from users.forms import UserRegisterForm, UserForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}'
        send_mail(
            subject='Подтверждение почты',
            message=f'Привет! Перейди по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
            )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserListView(LoginRequiredMixin, ListView, PermissionRequiredMixin):
    model = User
    template_name = 'user_list.html'
    permission_required = 'users.can_view_user'


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['id', 'email', 'is_active', ]
    success_url = reverse_lazy('users:user_list')

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('users.can_view_user') and user.has_perm('users.can_block_user'):
            return UserForm
        raise PermissionDenied


class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('users:user_list')

users/templates/users/user_confirm_delete.html
{% extends 'mail/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-8">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить пользователя {{ object.email }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-danger">Удалить пользователя</button>
                    <a class="btn btn-primary" href="{% url 'users:user_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'mail/base.html' %}
{% block content %}

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Пользователь: {{ object.email }} </h1>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">Почта пользователя: {{ object.email }}</p>
              <p class="card-text">Телефон пользователя: {{ object.phone }}</p>
                <p class="card-text">Страна пользователя: {{ object.country }}</p>
              <p class="card-text">Статус пользователя: {{ object.is_active }}</p>

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'users:user_list' %}" role="button">Назад</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</main>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mail/base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-4">
            <div class="card">
                <p></p>

                <p class="card-text">Пользователь: {{ object.email }}</p>

                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Обновить статус пользователя
                    {% else %}
                    Зарегистрироваться
                    {% endif %}
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mail/base.html' %}
{% block content %}

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Список Пользователей</h1>
        <a href="#" class="btn btn-primary my-2">Добавить нового пользователя</a>
      </div>
    </div>
  </section>

  {% if perms.users.can_view_user %}
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for user in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">Почта: {{ user.email }}</p>
              <p class="card-text">Активен: {{ user.is_active }}</p>
              <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'users:user_detail' user.pk %}" role="button">Посмотреть</a>
                  <a class="btn btn-primary" href="{% url 'users:user_update' user.pk %}" role="button">Блокировка/Разблокировка</a>
                  <a class="btn btn-primary" href="{% url 'users:user_delete' user.pk %}" role="button">Удалить</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endif %}

</main>

{% endblock %}